replicaCount: 1

image:
  repository: shadhir03/discovery-server
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8761
  targetPort: 8761

resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 50m
    memory: 128Mi
